name: clarifi_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Packages
  app_links: ^6.3.0
  fl_chart: ^1.1.1
  uuid: ^4.4.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.1.5+1

  # Routing
  go_router: ^16.2.4

  # Supabase
  supabase_flutter: ^2.10.2
  flutter_dotenv: ^6.0.0

  # HTTP client
  http: ^1.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo.png
    - lib/assets/logo-figura.png
    - lib/assets/onboarding-page-1.png
    - lib/assets/onboarding-page-2.png
    - lib/assets/onboarding-page-3.png
    - lib/assets/Overlay.png
